-- ============================================================
-- Migration 002: Seed initial rules for v1 rule engine
-- ============================================================

INSERT INTO rules (code, name, description, rule_group, severity, measure_types, logic, explanation_template, source_refs, is_blocking, is_active)
VALUES

-- SØKNADSPLIKT
('SØKP-001',
 'Søknadsplikt: Bruksendring til boenhet',
 'Bruksendring til ny boenhet er alltid søknadspliktig etter PBL § 20-1',
 'søknadsplikt',
 'fail',
 '["bruksendring"]',
 '{"condition": "measure_type == ''bruksendring'' AND new_dwelling_unit == true", "result": "application_required"}',
 'Bruksendring til ny boenhet krever søknad etter plan- og bygningsloven § 20-1 bokstav d.',
 '["PBL § 20-1 bokstav d"]',
 TRUE,
 TRUE),

('SØKP-002',
 'Søknadsplikt: Tilbygg over 15 m²',
 'Tilbygg over 15 m² er søknadspliktig. Under 15 m² kan være unntatt etter § 20-5.',
 'søknadsplikt',
 'warn',
 '["tilbygg", "påbygg"]',
 '{"condition": "measure_type IN (''tilbygg'', ''påbygg'')", "result": "likely_application_required"}',
 'Tilbygg er normalt søknadspliktig etter PBL § 20-1. Tilbygg under 15 m² kan i noen tilfeller være unntatt etter § 20-5 – dette krever nærmere vurdering.',
 '["PBL § 20-1 bokstav b", "PBL § 20-5"]',
 FALSE,
 TRUE),

('SØKP-003',
 'Mulig unntak fra søknadsplikt (§ 20-5)',
 'Visse mindre tiltak kan være unntatt søknadsplikt etter PBL § 20-5',
 'søknadsplikt',
 'info',
 '["garasje", "carport", "støttemur", "veranda"]',
 '{"condition": "measure_type IN (''garasje'', ''carport'', ''støttemur'', ''veranda'')", "result": "check_exemption"}',
 'Tiltaket kan potensielt være unntatt søknadsplikt etter PBL § 20-5 dersom det oppfyller alle vilkår (størrelse, avstand til nabogrense, ikke i strid med plan m.m.). Sjekk kommunens veiledning.',
 '["PBL § 20-5", "SAK10 § 4-1"]',
 FALSE,
 TRUE),

-- PLANSTATUS
('PLAN-001',
 'Tiltak i strid med reguleringsplan',
 'Tiltak som er i strid med gjeldende reguleringsplan krever dispensasjon',
 'planstatus',
 'fail',
 '[]',
 '{"condition": "plan_status == ''regulert'' AND areal_formal NOT IN (''boligbebyggelse'', ''fritidsbebyggelse'')", "result": "potential_conflict"}',
 'Eiendommen er regulert til et formål som kan være i strid med det planlagte tiltaket. Tiltak i strid med reguleringsplan krever dispensasjon etter PBL § 19-1.',
 '["PBL § 19-1", "PBL § 12-4"]',
 TRUE,
 TRUE),

('PLAN-002',
 'Tiltak i LNF-område',
 'Tiltak i LNF-område (Landbruk, Natur og Friluft) er normalt ikke tillatt',
 'planstatus',
 'fail',
 '[]',
 '{"condition": "areal_formal == ''LNF''", "result": "not_permitted"}',
 'Eiendommen ligger i et LNF-område (Landbruk, Natur og Friluft). Byggetiltak er normalt ikke tillatt i LNF-områder uten dispensasjon.',
 '["PBL § 11-7 nr. 5", "PBL § 19-1"]',
 TRUE,
 TRUE),

('PLAN-003',
 'Hensynssone – krav om særskilt vurdering',
 'Eiendommen er berørt av en eller flere hensynssoner',
 'planstatus',
 'warn',
 '[]',
 '{"condition": "hensynssoner.length > 0", "result": "special_consideration"}',
 'Eiendommen er berørt av hensynssone(r). Hensynssoner kan gi særskilte krav til utforming, materialbruk eller prosess.',
 '["PBL § 11-8"]',
 FALSE,
 TRUE),

-- FAREDATA
('FARE-001',
 'Tiltak i flomsone',
 'Tiltak i flomsone krever særskilt vurdering og dokumentasjon',
 'naturfare',
 'fail',
 '[]',
 '{"condition": "flom_fare IN (''middels'', ''høy'')", "result": "flood_risk"}',
 'Eiendommen ligger i et område med flomfare. Tiltak i flomsoner krever særskilt vurdering etter TEK17 § 7-2 og dokumentasjon av at sikkerhetskravene er oppfylt.',
 '["TEK17 § 7-2", "NVE retningslinjer"]',
 TRUE,
 TRUE),

('FARE-002',
 'Tiltak i skredfareområde',
 'Tiltak i skredfareområde krever særskilt vurdering og dokumentasjon',
 'naturfare',
 'fail',
 '[]',
 '{"condition": "skred_fare IN (''middels'', ''høy'')", "result": "landslide_risk"}',
 'Eiendommen ligger i et område med skredfare. Tiltak i skredfareområder krever særskilt geoteknisk vurdering og dokumentasjon etter TEK17 § 7-3.',
 '["TEK17 § 7-3", "NVE retningslinjer"]',
 TRUE,
 TRUE),

-- DOKUMENTKRAV
('DOK-001',
 'Dokumentkrav: Situasjonsplan',
 'Alle søknadspliktige tiltak krever situasjonsplan',
 'dokumentkrav',
 'info',
 '[]',
 '{"condition": "application_required == true", "result": "require_document"}',
 'Søknadspliktige tiltak krever situasjonsplan som viser eiendommens grenser, eksisterende og planlagte bygninger, samt avstander til nabogrenser.',
 '["SAK10 § 5-4"]',
 FALSE,
 TRUE),

('DOK-002',
 'Dokumentkrav: Tegninger',
 'Alle søknadspliktige tiltak krever plan-, fasade- og snittegninger',
 'dokumentkrav',
 'info',
 '[]',
 '{"condition": "application_required == true", "result": "require_document"}',
 'Søknadspliktige tiltak krever plan-, fasade- og snittegninger i målestokk som viser tiltaket tydelig.',
 '["SAK10 § 5-4"]',
 FALSE,
 TRUE),

('DOK-003',
 'Dokumentkrav: Nabovarsel',
 'Alle søknadspliktige tiltak krever nabovarsel',
 'dokumentkrav',
 'info',
 '[]',
 '{"condition": "application_required == true", "result": "require_document"}',
 'Søknadspliktige tiltak krever at naboer og gjenboere varsles i henhold til PBL § 21-3.',
 '["PBL § 21-3", "SAK10 § 5-2"]',
 FALSE,
 TRUE),

-- DISPENSASJON
('DISP-001',
 'Dispensasjonsindikator: Planstrid',
 'Tiltaket kan kreve dispensasjon fra reguleringsplan',
 'dispensasjon',
 'warn',
 '[]',
 '{"condition": "plan_conflict == true", "result": "dispensation_likely"}',
 'Tiltaket kan være i strid med reguleringsplanen. Dispensasjon etter PBL § 19-1 kan søkes, men innvilges kun dersom fordelene er vesentlig større enn ulempene, og tiltaket ikke er i strid med nasjonale eller regionale interesser.',
 '["PBL § 19-1", "PBL § 19-2"]',
 FALSE,
 TRUE)

ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    logic = EXCLUDED.logic,
    explanation_template = EXCLUDED.explanation_template,
    source_refs = EXCLUDED.source_refs,
    is_blocking = EXCLUDED.is_blocking,
    updated_at = NOW();
